apiVersion: apps/v1
kind: Deployment
metadata:
  name: slide-service
  labels:
    app: slide-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slide-service
  template:
    metadata:
      labels:
        app: slide-service
    spec:
      containers:
      - name: slide-service
        image: dockerhub.airamatrix.in:50000/slide-service:latest
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082
        env:
        # - name: SPRING_JPA_DATABASE
        #   value: docker-mysql
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://docker-mysql:3306/microservices?useSSL=false
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: slide-service
  labels:
    app: slide-service
spec:
  ports:
  - port: 8082
    protocol: TCP
  selector:
    app: slide-service