server:
  port: 8082
  
logging:
  level:
    root: INFO
    org.springframework.web: TRACE
    org.springframework.security.oauth2: TRACE
    org.springframework.cloud: INFO
    org.springframework.security: TRACE
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    healthcheck:
      enabled: true
spring:
  application:
    name: resource-server
## Comment start : Adding the below properties resulted in getting invalid access token from resource server.     
#   security:
#     oauth2:
#       resourceserver:
#         opaquetoken:
#           introspection-uri: http://localhost:8080/oauth/check_token
#           client-id: clientId
#           client-secret: secret
# Comment end
  jackson:
    serialization:
      INDENT_OUTPUT: true