apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-server
  template:
    metadata:
      labels:
        app: auth-server
    spec:
      containers:
      - name: auth-server
        image: dockerhub.airamatrix.in:50000/auth-server:latest
        # imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9191
        env:
        # - name: SPRING_JPA_DATABASE
        #   value: docker-mysql
        - name: SPRING_DATASOURCE_URL
          value: jdbc:mysql://docker-mysql:3306/oauthDB?createDatabaseIfNotExist=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useSSL=false&failOverReadOnly=false&maxReconnects=10&allowPublicKeyRetrieval=true
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_USER
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: auth-server
  labels:
    app: auth-server
spec:
  ports:
  - port: 9191
    protocol: TCP
  selector:
    app: auth-server